# .sops.yaml
creation_rules:
  - gcp_kms: projects/python-project-cluster/locations/northamerica-northeast2/keyRings/key/cryptoKeys/key
    # Specify any file patterns you want to auto-encrypt
    path_regex: '.*\.yml|yaml$'
    encrypted_regex: '^(secrets)$'